/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */
import type { AnimeReactReaction } from './animeReactReaction'

export interface AnimeReact {
  reaction?: AnimeReactReaction
}
