/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export type AnimeReactReaction =
  (typeof AnimeReactReaction)[keyof typeof AnimeReactReaction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimeReactReaction = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const
