/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export interface ChildEpisode {
  readonly id?: number;
  /**
   * @minimum -32768
   * @maximum 32767
   */
  order: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}
