/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export interface ChildTeam {
  readonly avatar?: string;
  readonly get_params?: string;
  readonly value?: string;
}
