/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */
import type { CommentReactReaction } from './commentReactReaction';

export interface CommentReact {
  reaction?: CommentReactReaction;
}
