/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export type CommentReactReaction = typeof CommentReactReaction[keyof typeof CommentReactReaction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentReactReaction = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
