/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export interface CreateComment {
  /** @minLength 1 */
  content: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  object_id: number;
  parent_id?: number;
}
