/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export interface EpisodeVoiceover {
  /**
   * @minLength 1
   * @maxLength 200
   */
  url: string
  readonly value?: string
}
