/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export interface ErrorComponent {
  /** @minLength 1 */
  location?: string;
  /** @minLength 1 */
  message: string;
}
