/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export type GetAnimeListStatus = typeof GetAnimeListStatus[keyof typeof GetAnimeListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAnimeListStatus = {
  CAME_OUT: 'CAME_OUT',
  COMES_OUT: 'COMES_OUT',
  ANNOUNCED: 'ANNOUNCED',
} as const;
