/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export type GetAnimeListType = typeof GetAnimeListType[keyof typeof GetAnimeListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAnimeListType = {
  SERIAL: 'SERIAL',
  FILM: 'FILM',
  ONA: 'ONA',
  OVA: 'OVA',
} as const;
