/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */
import type { GetAnimeListCountry } from './getAnimeListCountry'
import type { GetAnimeListStatus } from './getAnimeListStatus'
import type { GetAnimeListType } from './getAnimeListType'
import type { GetAnimeListSeason } from './getAnimeListSeason'

export type GetAnimeListParams = {
  /**
   * Genres.
   */
  genres?: string
  /**
   * Studio.
   */
  studio?: string
  /**
   * Country.
   */
  country?: GetAnimeListCountry
  /**
   * Status.
   */
  status?: GetAnimeListStatus
  /**
   * Director.
   */
  director?: string
  /**
   * Type.
   */
  type?: GetAnimeListType
  /**
   * Voiceover.
   */
  voiceover?: string
  /**
   * Season.
   */
  season?: GetAnimeListSeason
  /**
   * Year_gte.
   */
  year_gte?: string
  /**
   * Year_lte.
   */
  year_lte?: string
  /**
   * Episode_lte.
   */
  episode_lte?: string
  /**
   * Episode_gte.
   */
  episode_gte?: string
  /**
   * A page number within the paginated result set.
   */
  page?: number
  /**
   * Number of results to return per page.
   */
  page_size?: number
}
