/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export type GetAnimeListSeason =
  (typeof GetAnimeListSeason)[keyof typeof GetAnimeListSeason]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAnimeListSeason = {
  WINTER: 'WINTER',
  SPRING: 'SPRING',
  SUMMER: 'SUMMER',
  FALL: 'FALL',
} as const
