/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */
import type { GetAnimeListCountry } from './getAnimeListCountry';
import type { GetAnimeListStatus } from './getAnimeListStatus';
import type { GetAnimeListType } from './getAnimeListType';
import type { GetAnimeListSeason } from './getAnimeListSeason';

export type GetAnimeListParams = {
/**
 * genres
 */
genres?: string;
/**
 * studio
 */
studio?: string;
/**
 * country
 */
country?: GetAnimeListCountry;
/**
 * status
 */
status?: GetAnimeListStatus;
/**
 * director
 */
director?: string;
/**
 * type
 */
type?: GetAnimeListType;
/**
 * voiceover
 */
voiceover?: string;
/**
 * season
 */
season?: GetAnimeListSeason;
/**
 * year_gte
 */
year_gte?: string;
/**
 * year_lte
 */
year_lte?: string;
/**
 * episode_lte
 */
episode_lte?: string;
/**
 * episode_gte
 */
episode_gte?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};
