/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export interface HelpAppeal {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string
  /** @minLength 1 */
  message: string
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string
}
