/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export type RequestUserAnimeAction =
  (typeof RequestUserAnimeAction)[keyof typeof RequestUserAnimeAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestUserAnimeAction = {
  FAVORITE: 'FAVORITE',
  VIEWED: 'VIEWED',
  DROPPED: 'DROPPED',
  PLANNED: 'PLANNED',
  WATCHING: 'WATCHING',
} as const
