/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */
import type { ResponseAnimeReactAction } from './responseAnimeReactAction';

export interface ResponseAnimeReact {
  action: ResponseAnimeReactAction;
}
