/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export interface ResponseUserLogout {
  /** @minLength 1 */
  refresh: string;
}
