/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */
import type { ErrorComponent } from './errorComponent';

export type ResponseErrorErrorsItem = {[key: string]: ErrorComponent};
