/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export type ResponseUserAnimeListAction = typeof ResponseUserAnimeListAction[keyof typeof ResponseUserAnimeListAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseUserAnimeListAction = {
  FAVORITE: 'FAVORITE',
  VIEWED: 'VIEWED',
  DROPPED: 'DROPPED',
  PLANNED: 'PLANNED',
  WATCHING: 'WATCHING',
} as const;
