/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */
import type { ResponseAnimeList } from './responseAnimeList';

export interface ResponseStudio {
  anime: ResponseAnimeList[];
  readonly created?: string;
  description?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
}
