/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export type ResponseCommentReactAction =
  (typeof ResponseCommentReactAction)[keyof typeof ResponseCommentReactAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseCommentReactAction = {
  DELETE: 'DELETE',
  CHANGE: 'CHANGE',
  NEW: 'NEW',
} as const
