/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export type ResponseAnimeListType = typeof ResponseAnimeListType[keyof typeof ResponseAnimeListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseAnimeListType = {
  SERIAL: 'SERIAL',
  FILM: 'FILM',
  ONA: 'ONA',
  OVA: 'OVA',
} as const;
