/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */
import type { Director } from './director';
import type { ChildEpisode } from './childEpisode';
import type { Genre } from './genre';
import type { ChildPreviewImage } from './childPreviewImage';
import type { ResponseAnimeReleaseDayOfWeek } from './responseAnimeReleaseDayOfWeek';
import type { ResponseAnimeList } from './responseAnimeList';
import type { Studio } from './studio';
import type { ChildTeam } from './childTeam';

export interface ResponseAnime {
  /**
   * in minutes
   * @minimum -32768
   * @maximum 32767
   * @nullable
   */
  average_time_episode?: number | null;
  /** @nullable */
  readonly background_image?: string | null;
  /** @nullable */
  readonly card_image?: string | null;
  readonly count_episodes?: string;
  readonly country?: string;
  description?: string;
  director: Director;
  /** @nullable */
  end_date?: string | null;
  episodes: ChildEpisode[];
  readonly genres?: readonly Genre[];
  readonly id?: number;
  images: ChildPreviewImage[];
  /** @minLength 1 */
  rating: string;
  related?: number[];
  /** @nullable */
  release_day_of_week?: ResponseAnimeReleaseDayOfWeek;
  readonly season?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  short_description?: string;
  similar: ResponseAnimeList[];
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  readonly start_date?: string;
  readonly status?: string;
  readonly studio?: readonly Studio[];
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  /**
   * @maxLength 200
   * @nullable
   */
  trailer_url?: string | null;
  readonly type?: string;
  voiceovers: ChildTeam[];
  /**
   * @minimum -32768
   * @maximum 32767
   */
  year: number;
}
