/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export type ResponseAnimeReactAction =
  (typeof ResponseAnimeReactAction)[keyof typeof ResponseAnimeReactAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseAnimeReactAction = {
  DELETE: 'DELETE',
  CHANGE: 'CHANGE',
  NEW: 'NEW',
} as const
