/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export interface ResponseCommentAnime {
  /** @minLength 1 */
  content_main: string;
  readonly created?: string;
  readonly get_count_dislike?: string;
  readonly get_count_like?: string;
  readonly has_reply?: string;
  readonly id?: number;
  /** @minLength 1 */
  readonly urlhash?: string;
  /** @minLength 1 */
  username: string;
}
