/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */

export interface ResponseUserSettings {
  /** @nullable */
  readonly avatar?: string | null;
  /** @maxLength 255 */
  telegram?: string;
}
