/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */
import type { ResponseAnimeList } from './responseAnimeList';

export interface ResponseDirector {
  anime: ResponseAnimeList[];
  readonly full_name?: string;
}
