/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

/**
 * @nullable
 */
export type ResponseAnimeReleaseDayOfWeek =
  | (typeof ResponseAnimeReleaseDayOfWeek)[keyof typeof ResponseAnimeReleaseDayOfWeek]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseAnimeReleaseDayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const
