/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV
 */
import type { User } from './user';

export interface ResponseUserRegister {
  /** @minLength 1 */
  access: string;
  /** @minLength 1 */
  refresh: string;
  user: User;
}
