/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */
import type { ResponseCommentReactAction } from './responseCommentReactAction'

export interface ResponseCommentReact {
  action: ResponseCommentReactAction
}
