/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */
import type { ResponseFiltersAnimeCountries } from './responseFiltersAnimeCountries'
import type { ResponseFiltersAnimeDirectors } from './responseFiltersAnimeDirectors'
import type { ResponseFiltersAnimeGenres } from './responseFiltersAnimeGenres'
import type { ResponseFiltersAnimeSeason } from './responseFiltersAnimeSeason'
import type { ResponseFiltersAnimeStatus } from './responseFiltersAnimeStatus'
import type { ResponseFiltersAnimeStudios } from './responseFiltersAnimeStudios'
import type { ResponseFiltersAnimeType } from './responseFiltersAnimeType'
import type { ResponseFiltersAnimeVoiceover } from './responseFiltersAnimeVoiceover'

export interface ResponseFiltersAnime {
  countries: ResponseFiltersAnimeCountries
  directors: ResponseFiltersAnimeDirectors
  genres: ResponseFiltersAnimeGenres
  season: ResponseFiltersAnimeSeason
  status: ResponseFiltersAnimeStatus
  studios: ResponseFiltersAnimeStudios
  type: ResponseFiltersAnimeType
  voiceover: ResponseFiltersAnimeVoiceover
}
