/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: 0.0.66 DEV
 */

export interface TokenRefresh {
  /** @minLength 1 */
  readonly access?: string;
  /** @minLength 1 */
  refresh: string;
}
