/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export interface TokenObtainPair {
  /** @minLength 1 */
  password: string
  /** @minLength 1 */
  username: string
}
