/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */

export interface User {
  count_commented_anime: number
  count_viewed_anime: number
  /** @minLength 1 */
  username: string
}
