/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Anime ON API
 * OpenAPI spec version: ##VERSION## DEV.
 */
import type { HelpAppeal, RightholderAppeal } from '../model'
import { customInstance } from '../custom-instance'

/**
 * Ellipsis.
 * @summary Ellipsis.
 */
export type createHelpAppealResponse = {
  data: unknown
  status: number
}

export const getCreateHelpAppealUrl = () => {
  return `/support/help/`
}

export const createHelpAppeal = async (
  helpAppeal: HelpAppeal,
  options?: RequestInit,
): Promise<createHelpAppealResponse> => {
  return customInstance<Promise<createHelpAppealResponse>>(
    getCreateHelpAppealUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(helpAppeal),
    },
  )
}

/**
 * Ellipsis.
 * @summary Ellipsis.
 */
export type createRightholderAppealResponse = {
  data: unknown
  status: number
}

export const getCreateRightholderAppealUrl = () => {
  return `/support/rightholder/`
}

export const createRightholderAppeal = async (
  rightholderAppeal: RightholderAppeal,
  options?: RequestInit,
): Promise<createRightholderAppealResponse> => {
  return customInstance<Promise<createRightholderAppealResponse>>(
    getCreateRightholderAppealUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(rightholderAppeal),
    },
  )
}
